from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PNG_DIR = ROOT / "visuals" / "png"
PDF_DIR = ROOT / "visuals" / "vector"
VA_VISUAL_ROOT = ROOT / "docs" / "states" / "virginia" / "visuals"
VA_PNG_DIR = VA_VISUAL_ROOT / "png"
VA_PDF_DIR = VA_VISUAL_ROOT / "vector"
OUT_MD = ROOT / "docs" / "figures" / "visual_packaging_manifest.md"


GROUPS: list[tuple[str, list[str]]] = [
    (
        "Main Figures",
        [
            "occupation_share_barh",
            "task_heatmap",
            "hours_timeseries",
            "transition_coarse_matrix_latest",
            "transition_summary_metrics",
            "figure2_redesigned_composite",
            "btos_ai_trends",
            "btos_workforce_effects_barh",
            "figure3_redesigned_composite",
            "jolts_openings_rate",
            "ces_payroll_index",
            "figure4_redesigned_composite",
            "capability_matrix_heatmap",
            "policy_roadmap",
        ],
    ),
    (
        "Appendix Figures",
        [
            "asec_mean_income",
            "sipp_event_employment",
            "cps_supp_mobility_share",
            "abs_measure_shares",
            "ces_payroll_index_mean",
            "bed_gross_job_gains",
            "qcew_top20_state_employment",
            "lehd_benchmark_rate",
            "top30_puma_high_ai_share",
            "nls_occupation_switch_rate",
        ],
    ),
    (
        "Memo Pack",
        [
            "memo_dashboard",
            "memo_btos_two_panel",
            "memo_cps_sankey",
            "memo_occ_bubble_scatter",
            "memo_btos_state_choropleth",
            "memo_resolution_ladder",
            "memo_capability_matrix",
            "memo_policy_roadmap",
        ],
    ),
    (
        "Virginia Pack",
        [
            "virginia_sector_composition",
            "virginia_sector_wages",
            "virginia_peers_sector_shares",
            "virginia_peers_sector_wages",
            "virginia_sector_ranks",
            "virginia_kpi_dashboard",
            "virginia_btos_state_highlight",
            "virginia_occ_context",
        ],
    ),
    (
        "Monitoring Metrics (AWES/ALPI)",
        [
            "awes_top20_latest",
            "alpi_top20_latest",
            "awes_alpi_monthly_median",
            "awes_vs_alpi_latest_scatter",
        ],
    ),
]


def _row(
    stem: str,
    *,
    png_dir: Path = PNG_DIR,
    pdf_dir: Path = PDF_DIR,
    png_rel: str = "visuals/png",
    pdf_rel: str = "visuals/vector",
) -> str:
    png = png_dir / f"{stem}.png"
    pdf = pdf_dir / f"{stem}.pdf"
    png_cell = f"`{png_rel}/{png.name}`" if png.is_file() else "`MISSING`"
    pdf_cell = f"`{pdf_rel}/{pdf.name}`" if pdf.is_file() else "`MISSING`"
    return f"| `{stem}` | {png_cell} | {pdf_cell} |"


def _row_virginia(stem: str) -> str:
    return _row(
        stem,
        png_dir=VA_PNG_DIR,
        pdf_dir=VA_PDF_DIR,
        png_rel="docs/states/virginia/visuals/png",
        pdf_rel="docs/states/virginia/visuals/vector",
    )


def main() -> None:
    lines: list[str] = ["# Visual Packaging Manifest", ""]
    lines.append(
        "Auto-generated by `scripts/build_visual_packaging_manifest.py`."
    )
    lines.append("")
    for name, stems in GROUPS:
        lines.append(f"## {name}")
        lines.append("| Stem | PNG | PDF |")
        lines.append("|---|---|---|")
        for stem in stems:
            if name == "Virginia Pack":
                lines.append(_row_virginia(stem))
            else:
                lines.append(_row(stem))
        lines.append("")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines).strip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
